export enum ContextActions {
  LOAD_SAVED_STATE,

  USER_FILE_INPUT,

  GRID_UPDATE,

  CLASSIFICATION_CONFIG,

  SPLUS_TRILOGY_CONFIG,
  SPLUS_IMAGING,
  SPLUS_LUPTON_CONFIG,
  SPLUS_PHOTO_SPECTRA,

  LEGACY_IMAGING,

  SDSS_IMAGING,
  SDSS_CATALOG,

  CUSTOM_IMAGE_NEW,
  CUSTOM_IMAGE_UPDATE,
  CUSTOM_IMAGE_REMOVE,
  CUSTOM_IMAGE_ENABLE,

  CURRENT_VIEW_CHANGE,

  SCATTER_PLOT_SETUP,
  COLOR_PLOT_SETUP,
  HISTOGRAM_PLOT_SETUP,
  PLOT_VIEW_CHANGE,
  PLOT_SETUP,
}